services:
  zyra:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: ["/bin/bash", ".devcontainer/entrypoint.sh"]
    profiles: ["dev"]
    volumes:
      - .:/app
      - ./data/uploads:/data/uploads
    environment:
      # Python settings
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1

      # App environment
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      VIMEO_CLIENT_ID: ${VIMEO_CLIENT_ID}
      VIMEO_CLIENT_SECRET: ${VIMEO_CLIENT_SECRET}
      VIMEO_ACCESS_TOKEN: ${VIMEO_ACCESS_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

      # Redis / API autostart (prefer ZYRA_*; fallback to legacy DATAVIZHUB_*)
      ZYRA_USE_REDIS: ${ZYRA_USE_REDIS:-${DATAVIZHUB_USE_REDIS:-0}}
      ZYRA_REDIS_URL: ${ZYRA_REDIS_URL:-${DATAVIZHUB_REDIS_URL:-redis://redis:6379/0}}
      ZYRA_AUTOSTART_API: ${ZYRA_AUTOSTART_API:-1}
      ZYRA_AUTOSTART_RQ: ${ZYRA_AUTOSTART_RQ:-${ZYRA_USE_REDIS:-${DATAVIZHUB_USE_REDIS:-0}}}
      ZYRA_UPLOAD_DIR: ${ZYRA_UPLOAD_DIR:-/data/uploads}
      ZYRA_MIN_DISK_MB: ${ZYRA_MIN_DISK_MB:-100}
      ZYRA_REQUIRE_FFMPEG: ${ZYRA_REQUIRE_FFMPEG:-0}

      # API network settings (prefer ZYRA_*)
      ZYRA_API_HOST: ${ZYRA_API_HOST:-0.0.0.0}
      ZYRA_API_PORT: ${ZYRA_API_PORT:-8000}

      # Back-compat: also set legacy names from ZYRA_* when missing
      DATAVIZHUB_USE_REDIS: ${DATAVIZHUB_USE_REDIS:-${ZYRA_USE_REDIS:-0}}
      DATAVIZHUB_REDIS_URL: ${DATAVIZHUB_REDIS_URL:-${ZYRA_REDIS_URL:-redis://redis:6379/0}}
      DATAVIZHUB_AUTOSTART_API: ${DATAVIZHUB_AUTOSTART_API:-${ZYRA_AUTOSTART_API:-1}}
      DATAVIZHUB_AUTOSTART_RQ: ${DATAVIZHUB_AUTOSTART_RQ:-${ZYRA_AUTOSTART_RQ:-0}}
      DATAVIZHUB_UPLOAD_DIR: ${DATAVIZHUB_UPLOAD_DIR:-${ZYRA_UPLOAD_DIR:-/data/uploads}}
      DATAVIZHUB_MIN_DISK_MB: ${DATAVIZHUB_MIN_DISK_MB:-${ZYRA_MIN_DISK_MB:-100}}
      DATAVIZHUB_REQUIRE_FFMPEG: ${DATAVIZHUB_REQUIRE_FFMPEG:-${ZYRA_REQUIRE_FFMPEG:-0}}
      DATAVIZHUB_API_HOST: ${DATAVIZHUB_API_HOST:-${ZYRA_API_HOST:-0.0.0.0}}
      DATAVIZHUB_API_PORT: ${DATAVIZHUB_API_PORT:-${ZYRA_API_PORT:-8000}}

    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/ready"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    depends_on:
      - redis

  redis:
    image: redis:7
    profiles: ["dev"]
    ports:
      - "6379:6379"
