services:
  datavizhub:
    build: .
    env_file:
      - .devcontainer/.env
    volumes:
      - .:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: ["sleep", "infinity"]
