name: Bump Version on PR from staging to main

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  bump-version:
    if: github.head_ref == 'staging'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: staging

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Cache Poetry cache and virtualenv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-

      # Optional if needed for plugins/scripts
      # - name: Install dependencies
      #   run: poetry install --no-root

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Bump patch version using Poetry
        run: |
          poetry version patch
          git add pyproject.toml
          git commit -m "ci: bump version" || echo "No changes to commit"
          git push origin staging
