name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write  # needed to push tags if tagging in CI

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # important for tags!

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry and plugin
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry self add poetry-dynamic-versioning
          poetry install --no-root

      - name: Run tests
        run: poetry run pytest --cov=src --cov-report=term-missing

      - name: Bump version and tag
        run: |
          VERSION=$(poetry version patch --short)
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "Release $VERSION"
          git tag "v$VERSION"
          git push origin main --tags

      - name: Build package
        run: poetry build

      - name: Publish to PyPI
        run: poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
